name: Publish NPM package

on:
  push:
    branches:
      - main

env:
  CLOUDAMQP_API_KEY: ${{ secrets.CLOUDAMQP_API_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ env.NPM_TOKEN }}
